apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin
  namespace: governance-system
spec:
  template:
    spec:
      nodeSelector:
        agentpool: "governance"
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "governance"
        effect: "NoSchedule"