apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  namespace: governance-system
data:
  config.json: |
    {
      "auths": {
        "registry.vultr.dndnordic.com": {
          "auth": "${VULTR_REGISTRY_AUTH_BASE64}"
        }
      }
    }