apiVersion: v1
kind: ConfigMap
metadata:
  name: origin-config
  namespace: governance-system
  labels:
    app: origin
    component: configuration
data:
  # Database redundancy configuration
  database-config.json: |
    {
      "databases": {
        "immutable_db": {
          "type": "immudb",
          "urls": [
            "immutable-db-0.immutable-db:3322",
            "immutable-db-1.immutable-db:3322"
          ],
          "options": {
            "max_retries": 5,
            "retry_delay": 2.0,
            "timeout": 30,
            "verify_connection": true
          }
        },
        "event_store": {
          "type": "eventstore",
          "urls": [
            "event-store-0.event-store:2113",
            "event-store-1.event-store:2113",
            "event-store-2.event-store:2113"
          ],
          "options": {
            "max_retries": 3,
            "retry_delay": 1.5,
            "timeout": 20
          }
        },
        "timescale_db": {
          "type": "postgresql",
          "urls": [
            "timescaledb-primary.governance-system:5432",
            "timescaledb-replica.governance-system:5432"
          ],
          "database": "origin",
          "options": {
            "application_name": "origin",
            "min_connections": 2,
            "max_connections": 10,
            "connect_timeout": 10
          }
        }
      },
      "fallback_strategy": "ordered_fallback",
      "health_check_interval": 30
    }
  
  # Redundancy and HA configuration
  ha-config.json: |
    {
      "ha_enabled": true,
      "node_health_port": 9090,
      "leader_election": {
        "enabled": true,
        "lease_duration": 15,
        "renew_deadline": 10,
        "retry_period": 2
      },
      "retry_policy": {
        "max_retries": 3,
        "backoff_factor": 2.0,
        "max_backoff": 30.0
      },
      "circuit_breaker": {
        "enabled": true,
        "failure_threshold": 5,
        "reset_timeout": 30
      },
      "distributed_lock": {
        "enabled": true,
        "timeout": 10,
        "ttl": 60
      }
    }
    
  # Vultr API integration configuration
  vultr-api-config.json: |
    {
      "api": {
        "vultr_api": {
          "base_url": "https://api.vultr.com/v2",
          "rate_limit": {
            "requests_per_second": 5,
            "burst": 10
          },
          "timeout": 30,
          "retry": {
            "max_attempts": 3,
            "backoff_factor": 2.0
          }
        },
        "container_registry": {
          "base_url": "https://registry.vultr.dndnordic.com/v2",
          "rate_limit": {
            "requests_per_second": 10,
            "burst": 20
          }
        },
        "object_storage": {
          "endpoint": "ewr1.vultrobjects.com",
          "region": "ewr",
          "buckets": {
            "backup": "origin-backups",
            "artifacts": "origin-artifacts",
            "logs": "origin-logs"
          },
          "backup_retention": {
            "daily": 7,
            "weekly": 4,
            "monthly": 3
          }
        },
        "inference_service": {
          "base_url": "https://inference.vultr.com/v1",
          "rate_limit": {
            "requests_per_minute": 100
          },
          "models": {
            "chat": "gpt-3.5-turbo",
            "completion": "text-davinci-003",
            "embeddings": "text-embedding-ada-002",
            "image": "dall-e-3"
          },
          "failover": {
            "primary_health_check_interval": 300,
            "failure_threshold": 3,
            "automatic_recovery": true
          }
        }
      },
      "services": {
        "backup": {
          "schedule": "0 1 * * *",  # Daily at 1 AM
          "types": ["database", "configuration", "state"],
          "compress": true,
          "encrypt": true
        },
        "container_registry": {
          "repositories": [
            "origin",
            "singularity-client",
            "governance-runner",
            "tailscale-ssh"
          ],
          "cleanup": {
            "untagged_images": {
              "retention_days": 7
            },
            "old_tags": {
              "retention_count": 10,
              "exclude_patterns": ["latest", "stable", "v*.*.*"]
            }
          }
        },
        "instance_management": {
          "auto_scaling": {
            "enabled": false,
            "min_instances": 1,
            "max_instances": 3,
            "cpu_threshold": 75,
            "memory_threshold": 80
          }
        },
        "inference": {
          "enabled": true,
          "model_mappings": {
            "singularity-local": "gpt-3.5-turbo",
            "singularity-large": "gpt-4",
            "mikael-fine-tuned": "gpt-3.5-turbo-16k",
            "singularity-embeddings": "text-embedding-ada-002"
          },
          "primary_inference": {
            "url": "http://mikael-wsl-connector.governance-system.svc.cluster.local:8000/v1",
            "timeout": 60
          },
          "backup_inference": {
            "url": "https://inference.vultr.com/v1",
            "timeout": 30
          }
        }
      }
    }