apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: origin-pvc
  namespace: governance-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard