apiVersion: v1
kind: Secret
metadata:
  name: origin-secrets
  namespace: governance-system
type: Opaque
data:
  github-token: ${GITHUB_TOKEN_BASE64}
  github-webhook-secret: ${GITHUB_WEBHOOK_SECRET_BASE64}
  mikael-auth-token: ${MIKAEL_AUTH_TOKEN_BASE64}
  dnd-genesis-github-token: ${DND_GENESIS_GITHUB_TOKEN_BASE64}
  github-runner-token: ${GITHUB_RUNNER_TOKEN_BASE64}
  mikael-wsl-host: ${MIKAEL_WSL_HOST_BASE64}
  mikael-wsl-port: ${MIKAEL_WSL_PORT_BASE64}
  mikael-wsl-user: ${MIKAEL_WSL_USER_BASE64}
  mikael-ssh-key: ${MIKAEL_SSH_KEY_BASE64}
  tailscale-auth-key: ${TAILSCALE_AUTH_KEY_BASE64}